// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxEwEt0f56nVjZamxqdsPt0kdTGit3PY0',
    appId: '1:465972803604:android:29d09ad4d082660dc7cf01',
    messagingSenderId: '465972803604',
    projectId: 'teste-estudo-299e9',
    databaseURL: 'https://teste-estudo-299e9-default-rtdb.firebaseio.com',
    storageBucket: 'teste-estudo-299e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnmiLS8AVcrvV8Bytn5JFVRjxiDhMf_2E',
    appId: '1:465972803604:ios:6cb2d063acc8d07dc7cf01',
    messagingSenderId: '465972803604',
    projectId: 'teste-estudo-299e9',
    databaseURL: 'https://teste-estudo-299e9-default-rtdb.firebaseio.com',
    storageBucket: 'teste-estudo-299e9.appspot.com',
    androidClientId: '465972803604-b2g63bnnghsviaddhibso2okics985it.apps.googleusercontent.com',
    iosClientId: '465972803604-00qndq6p9v71j9pm1626v0i16p060ubp.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChat',
  );
}
